package report

import (
	"fmt"
	"sort"
	"strings"

	"github.com/pocketninja/audisai/pkg/models"
)

// GenerateMarkdown creates a compliance report in Markdown format
func GenerateMarkdown(results []models.ScanResult, filesScanned int, policies []*models.Policy) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# AudisAI Compliance Report\n\n")

	// Summary
	sb.WriteString("## Summary\n\n")
	sb.WriteString(fmt.Sprintf("- **Files Scanned:** %d\n", filesScanned))
	sb.WriteString(fmt.Sprintf("- **Violations Found:** %d\n", len(results)))
	sb.WriteString(fmt.Sprintf("- **Policies Checked:** %d\n", len(policies)))
	sb.WriteString("\n")

	// Severity breakdown
	severityCounts := map[string]int{
		"CRITICAL": 0,
		"HIGH":     0,
		"MEDIUM":   0,
		"LOW":      0,
	}
	for _, r := range results {
		severityCounts[r.Severity]++
	}

	sb.WriteString("### Severity Breakdown\n\n")
	sb.WriteString(fmt.Sprintf("| 🔴 Critical | 🟠 High | 🟡 Medium | 🟢 Low |\n"))
	sb.WriteString(fmt.Sprintf("|:-----------:|:-------:|:---------:|:------:|\n"))
	sb.WriteString(fmt.Sprintf("| %d | %d | %d | %d |\n\n",
		severityCounts["CRITICAL"],
		severityCounts["HIGH"],
		severityCounts["MEDIUM"],
		severityCounts["LOW"]))

	if len(results) == 0 {
		sb.WriteString("✅ **No compliance violations detected!**\n\n")
		return sb.String()
	}

	// Group results by policy
	resultsByPolicy := make(map[string][]models.ScanResult)
	for _, r := range results {
		key := r.PolicyID
		resultsByPolicy[key] = append(resultsByPolicy[key], r)
	}

	// Sort policy keys for consistent output
	policyKeys := make([]string, 0, len(resultsByPolicy))
	for k := range resultsByPolicy {
		policyKeys = append(policyKeys, k)
	}
	sort.Strings(policyKeys)

	// Violations table grouped by policy
	sb.WriteString("## Violations\n\n")

	for _, policyID := range policyKeys {
		policyResults := resultsByPolicy[policyID]
		if len(policyResults) == 0 {
			continue
		}

		// Get policy name
		policyName := policyResults[0].PolicyName
		sb.WriteString(fmt.Sprintf("### %s\n\n", policyName))

		// Sort by severity then line number
		sort.Slice(policyResults, func(i, j int) bool {
			si := severityRank(policyResults[i].Severity)
			sj := severityRank(policyResults[j].Severity)
			if si != sj {
				return si < sj
			}
			return policyResults[i].LineNumber < policyResults[j].LineNumber
		})

		sb.WriteString("| Severity | Rule ID | File | Line | Violation |\n")
		sb.WriteString("|:--------:|:--------|:-----|:----:|:----------|\n")

		for _, r := range policyResults {
			severityIcon := severityIcon(r.Severity)
			snippet := truncate(r.Snippet, 50)
			lineStr := "-"
			if r.LineNumber > 0 {
				lineStr = fmt.Sprintf("%d", r.LineNumber)
			}

			sb.WriteString(fmt.Sprintf("| %s %s | `%s` | `%s` | %s | %s |\n",
				severityIcon, r.Severity, r.RuleID, r.FilePath, lineStr, snippet))
		}
		sb.WriteString("\n")
	}

	// Remediation section
	sb.WriteString("## Remediation Guidance\n\n")

	// Group by unique rule IDs
	remediationByRule := make(map[string]models.ScanResult)
	for _, r := range results {
		if _, exists := remediationByRule[r.RuleID]; !exists {
			remediationByRule[r.RuleID] = r
		}
	}

	// Sort rule IDs
	ruleIDs := make([]string, 0, len(remediationByRule))
	for k := range remediationByRule {
		ruleIDs = append(ruleIDs, k)
	}
	sort.Strings(ruleIDs)

	for _, ruleID := range ruleIDs {
		r := remediationByRule[ruleID]
		sb.WriteString(fmt.Sprintf("### `%s`: %s\n\n", ruleID, r.Message))
		sb.WriteString(fmt.Sprintf("> %s\n\n", r.Remediation))
	}

	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString("*Report generated by [AudisAI](https://github.com/pocketninja/audisai) - AI Compliance Static Analysis Tool*\n")

	return sb.String()
}

func severityRank(s string) int {
	switch s {
	case "CRITICAL":
		return 0
	case "HIGH":
		return 1
	case "MEDIUM":
		return 2
	case "LOW":
		return 3
	default:
		return 4
	}
}

func severityIcon(s string) string {
	switch s {
	case "CRITICAL":
		return "🔴"
	case "HIGH":
		return "🟠"
	case "MEDIUM":
		return "🟡"
	case "LOW":
		return "🟢"
	default:
		return "⚪"
	}
}

func truncate(s string, maxLen int) string {
	// Replace pipe characters to avoid breaking table formatting
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.TrimSpace(s)

	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}
