// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearOutput():Promise<void>;

export function GetAuthStatus():Promise<string>;

export function GetAvailableStates():Promise<Array<Record<string, string>>>;

export function GetOutput():Promise<Array<string>>;

export function IsScanning():Promise<boolean>;

export function SelectFolder():Promise<string>;

export function StartScan(arg1:main.ScanOptions):Promise<void>;
