// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearOutput() {
  return window['go']['main']['App']['ClearOutput']();
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetAvailableStates() {
  return window['go']['main']['App']['GetAvailableStates']();
}

export function GetOutput() {
  return window['go']['main']['App']['GetOutput']();
}

export function IsScanning() {
  return window['go']['main']['App']['IsScanning']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}
